<div>
    <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-[0.18em] text-hotel-700">Operations</p><h2 class="mt-1 text-2xl font-black text-slate-950">Lost & Found</h2><p class="mt-1 text-sm text-slate-500">Catat, simpan, dan telusuri barang temuan sampai dikembalikan.</p></div><div class="grid gap-2 sm:grid-cols-2"><input wire:model.live.debounce.250ms="search" class="form-input" placeholder="Kode, barang, lokasi..."><select wire:model.live="statusFilter" class="form-input"><option value="">Semua status</option>@foreach($statuses as $status)<option value="{{ $status->value }}">{{ $status->label() }}</option>@endforeach</select></div></div>
    <x-alert-notification />
    @error('lostFound')<div class="mb-5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">{{ $message }}</div>@enderror

    @can('lost_found.create')
        <section class="panel mb-5 p-5"><h3 class="font-bold text-slate-900">Catat barang temuan</h3><div class="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><div><label class="form-label">Nama barang</label><input wire:model="itemName" class="form-input" placeholder="Contoh: charger hitam">@error('itemName')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label">Lokasi ditemukan</label><input wire:model="foundLocation" class="form-input" placeholder="Room / area">@error('foundLocation')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label">Tanggal</label><input wire:model="foundDate" type="date" class="form-input"></div><div><label class="form-label">Lokasi penyimpanan</label><input wire:model="storageLocation" class="form-input" placeholder="Locker FO A-01"></div><div class="md:col-span-2"><label class="form-label">Reservasi terkait</label><select wire:model="reservationId" class="form-input"><option value="">Tidak diketahui</option>@foreach($reservations as $reservation)<option value="{{ $reservation->id }}">{{ $reservation->reservation_number }} · {{ $reservation->guest->full_name }}</option>@endforeach</select></div><div><label class="form-label">Foto</label><input wire:model="photo" type="file" accept="image/jpeg,image/png,image/webp" class="form-input">@error('photo')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label">Catatan</label><input wire:model="notes" class="form-input" placeholder="Ciri-ciri khusus"></div><div class="md:col-span-2 xl:col-span-4"><label class="form-label">Deskripsi</label><textarea wire:model="description" class="form-input" placeholder="Deskripsi detail barang..."></textarea></div></div><button wire:click="save" class="btn-primary mt-4">Simpan barang temuan</button></section>
    @endcan

    <div class="grid gap-4 xl:grid-cols-2">
        @forelse($items as $item)
            @php($tone = match($item->status->value) { 'FOUND' => 'bg-amber-100 text-amber-700', 'STORED' => 'bg-sky-100 text-sky-700', 'CLAIMED' => 'bg-violet-100 text-violet-700', 'RETURNED' => 'bg-emerald-100 text-emerald-700', default => 'bg-slate-100 text-slate-600' })
            <article wire:key="lost-found-{{ $item->id }}" class="panel p-5"><div class="flex items-start justify-between gap-4"><div><span class="badge {{ $tone }}">{{ $item->status->label() }}</span><h3 class="mt-3 text-lg font-black text-slate-950">{{ $item->item_name }}</h3><p class="text-xs font-bold text-slate-400">{{ $item->code }}</p></div><div class="text-right text-xs text-slate-500"><p>{{ $item->found_date->format('d M Y') }}</p><p class="mt-1">{{ $item->found_location }}</p></div></div><p class="mt-3 text-sm text-slate-600">{{ $item->description ?: 'Tidak ada deskripsi.' }}</p><div class="mt-4 grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-3 text-xs"><div><span class="text-slate-500">Guest terkait</span><p class="mt-0.5 font-bold text-slate-800">{{ $item->guest?->full_name ?? 'Belum diketahui' }}</p></div><div><span class="text-slate-500">Penyimpanan</span><p class="mt-0.5 font-bold text-slate-800">{{ $item->storage_location ?: 'Belum ditentukan' }}</p></div><div><span class="text-slate-500">Ditemukan oleh</span><p class="mt-0.5 font-bold text-slate-800">{{ $item->finder->name }}</p></div><div><span class="text-slate-500">Bukti foto</span><p class="mt-0.5 font-bold text-slate-800">{{ $item->photo ? 'Tersimpan aman' : 'Tidak ada' }}</p></div></div>
                @can('lost_found.update')
                    @if(!in_array($item->status->value, ['RETURNED','DISPOSED'], true))
                        <input wire:model="statusNotes.{{ $item->id }}" class="form-input mt-4" placeholder="Catatan perubahan status...">
                        <div class="mt-2 flex flex-wrap gap-2">@if($item->status->value === 'FOUND')<button wire:click="setStatus({{ $item->id }}, 'STORED')" class="btn-secondary">Simpan</button>@endif @if(in_array($item->status->value, ['FOUND','STORED'], true))<button wire:click="setStatus({{ $item->id }}, 'CLAIMED')" class="btn-secondary">Diklaim</button>@endif @if($item->status->value === 'CLAIMED')<button wire:click="setStatus({{ $item->id }}, 'RETURNED')" class="btn-primary">Dikembalikan</button>@endif <button wire:click="setStatus({{ $item->id }}, 'DISPOSED')" data-confirm="Item akan ditandai sebagai disposed dan tidak dapat diproses sebagai barang aktif lagi." data-confirm-title="Dispose barang temuan?" data-confirm-label="Ya, tandai disposed" data-confirm-tone="danger" class="btn-danger">Disposed</button></div>
                    @endif
                @endcan
            </article>
        @empty<div class="panel col-span-full px-6 py-16 text-center text-sm text-slate-500">Belum ada barang temuan.</div>@endforelse
    </div>
    @if($items->hasPages())<div class="mt-5">{{ $items->links() }}</div>@endif
</div>
